services:
    googleapis.maps.js:
        class: CoreBundle\GoogleApis\Js\PlacesApi
        arguments: [%googleapis.maps.key%]

    core.twig_extension:
        class: CoreBundle\Twig\CoreExtension
        arguments: [@googleapis.maps.js]
        tags:
            - { name: twig.extension}