services:
    googleapis.maps.js:
        class: CoreBundle\GoogleApis\Js\PlacesApi
        arguments: ["@=container.hasParameter('googleapis.maps.key') ? parameter('googleapis.maps.key') : null"]

    core.twig_extension:
        class: CoreBundle\Twig\CoreExtension
        arguments: [@googleapis.maps.js]
        tags:
            - { name: twig.extension}